# fly.toml app configuration file generated for artisan-fe on 2023-07-04T04:24:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "artisan-fe"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
